### ISSUE TITLE
Text going out of the page

### ISSUE THREAD

**Issue by lhoupert** [bpj/pandoc-attr-color#6]
Hi. it seems that I have a bug when I am highlighting a text that is longer than a standard line.

The code below:

```markdown
We dealt with the multiple sensor frequencies and their asynchronicity by re-sampling, for each flight, all the input and output time-series on a common 10Hz time vector **[following a backward filling method blablalblalblabla]{bg=yellow}[(Commentaire Loic: À vérifier)]{fg=red}**.
```

Results in this: 

![image](https://user-images.githubusercontent.com/10154151/112996928-88a1e300-9164-11eb-8c9c-5e1c1fc69d09.png)

I am forgetting something? I am using the last version of the filter.

**Comment by bpj** [comment]
Is this in LaTeX? All colored boxes (all boxes in fact) are unbreakable in LaTeX. This is a LaTeX limitation which this filter neither causes nor can work around.

**Comment by lhoupert** [comment]
Thank you for the quick reply!
Yes it is in Latex.
I didn't realise it was a latex limitation...I will stop myself using to
background color for long text :-)

Thank you.
